### ISSUE TITLE
Having a strange issue

### ISSUE THREAD

**Issue by DasKatzchen** [insidegadgets/GBCartRead#1]
I can't get GBCartRead to read the header correctly.  It reads the title as a bunch of garbled nonsense (but consistent nonsense - it's always the same nonsense for the same cart) but all the rest of the header information is correct. If I slip a piece of card behind the cartridge in an attempt to get better contact, it can suddenly read the title but now everything else is "unknown."  If I try to read it when the title is garbled (by altering the for-loop to make the title all zeros) it reads the rom but bgb complains about an invalid opcode on boot.  If I try to read it when the title is fine it stops after 32K.

**Comment by insidegadgets** [comment]
Hi DieKatzchen,

When it reads the title successfully, how does the ROM banks read - is it more than 1?
Sounds like you may have a loose connection on the board when pressure is applied to the GB slot, can you resolder the GB slot?
Also, for more tests, try to lower the baud rate to say 57600 and also add a longer delays when writing to the shift registers and when reading a byte.

I have heard of other people with similar issues (but not exactly the same as you see), turned out to be the Arduino they used wasn't outputting 5V correctly on pin 13 so we had to assign that pin to another one, though that was for an older version of GBCartRead (before we used SPI).

**Comment by DasKatzchen** [comment]
I can't get it to do it any more, but this is what it looked like when the title read successfully:

```
Game title... POKEMON YELLOW
MBC type... not found
ROM size... not found
RAM size... not found
```

Same game, without the card:

```
Game title... ═Ö☺═Ñ☺═Ö☺═Ñ☺OW
MBC type... MBC5+RAM+BATTERY
ROM size... 1MByte (64 banks)
RAM size... 32 KBytes (4 banks of 8Kbytes)`
```

For comparison, here's pokemon blue, in case it helps somehow.  it should read POKEMON BLUE:

```
Game title... ╦7G>►α
MBC type... MBC3+RAM+BATTERY
ROM size... 1MByte (64 banks)
RAM size... 32 KBytes (4 banks of 8Kbytes)
```

**Comment by DasKatzchen** [comment]
Broke out the multimeter, wrote a quick test sketch that just sets pin 13 as output then pulls it high and leaves it there.  I got a pretty inconsistent reading, sometimes 5V but usually around 1.5V.  I guess that's what I get for buying a cheap clone. I'm going to see if getting a power supply evens it out.
